# Generated by Django 3.2 on 2021-04-25 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название альбома')),
                ('date_of_release', models.DateField(verbose_name='Дата выпуска')),
                ('description', models.TextField(verbose_name='Описание альбома')),
                ('cover', models.ImageField(upload_to='images/albums_covers')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='Имя исполнителя')),
                ('last_name', models.CharField(max_length=40, verbose_name='Фамилия исполнителя')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('photo', models.ImageField(upload_to='images/artists_photos')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название плейлиста')),
                ('description', models.TextField(verbose_name='Описание жанра')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название плейлиста')),
                ('description', models.TextField(verbose_name='Описание плейлиста')),
                ('photo', models.ImageField(upload_to='images/playlists_covers')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Название трека')),
                ('soundtrack', models.FileField(upload_to='tracks/')),
                ('cover', models.ImageField(upload_to='images/artists_photos')),
                ('album', models.ManyToManyField(related_name='tracks', to='api.Album')),
                ('artists', models.ManyToManyField(related_name='tracks', to='api.Artist')),
                ('date_of_release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.album', verbose_name='Дата выпуска')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(related_name='albums', to='api.Artist'),
        ),
    ]
