# Generated by Django 3.2 on 2021-04-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210425_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='genres',
            field=models.ManyToManyField(related_name='tracks', to='api.Genre'),
        ),
    ]
