# Generated by Django 3.2 on 2021-04-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_track_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='date_of_release',
        ),
        migrations.AddField(
            model_name='track',
            name='date_of_release',
            field=models.DateField(auto_now=True, verbose_name='Дата выпуска'),
        ),
    ]
