# Generated by Django 3.2 on 2021-04-25 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210425_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='date_of_release',
            field=models.DateField(default=datetime.datetime(2021, 4, 25, 13, 47, 23, 378690), verbose_name='Дата выпуска'),
        ),
    ]
