# Generated by Django 3.2 on 2021-04-25 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210425_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='track',
        ),
        migrations.AddField(
            model_name='playlist',
            name='track',
            field=models.ManyToManyField(related_name='playlist', to='api.Track'),
        ),
        migrations.AlterField(
            model_name='album',
            name='date_of_release',
            field=models.DateField(default=datetime.datetime(2021, 4, 25, 13, 51, 50, 8373), verbose_name='Дата выпуска'),
        ),
        migrations.AlterField(
            model_name='track',
            name='date_of_release',
            field=models.DateField(default=datetime.datetime(2021, 4, 25, 13, 51, 50, 7371), verbose_name='Дата выпуска'),
        ),
    ]
