# Generated by Django 3.2 on 2021-05-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210425_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='genres',
            field=models.ManyToManyField(related_name='genres_tracks', to='api.Track'),
        ),
    ]
