# Generated by Django 3.2 on 2021-05-01 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_genre_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genres',
            new_name='tracks_list',
        ),
    ]
