# Generated by Django 3.2 on 2021-05-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_genre_tracks_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='about',
            field=models.TextField(default='', verbose_name='Об исполнителе'),
        ),
        migrations.AddField(
            model_name='track',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
    ]
