# Generated by Django 3.2 on 2021-05-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210506_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='cover',
            field=models.ImageField(blank=True, upload_to='images/genres_covers'),
        ),
    ]
