# Generated by Django 3.2 on 2021-05-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_genre_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='type_of_album',
            field=models.CharField(choices=[('Сингл', 'Сингл'), ('EP', 'EP'), ('Альбом', 'Альбом')], default='Альбом', max_length=6, verbose_name='Тип альбома'),
        ),
    ]
