# Generated by Django 3.2 on 2021-06-16 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_favoriteplaylist_favoriteplaylists'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritealbums',
            options={'verbose_name': 'Избранный альбом', 'verbose_name_plural': 'Избранные альбомы'},
        ),
        migrations.AlterModelOptions(
            name='favoriteartists',
            options={'verbose_name': 'Избранный исполнитель', 'verbose_name_plural': 'Избранные исполнители'},
        ),
        migrations.AlterModelOptions(
            name='favoritegenres',
            options={'verbose_name': 'Избранный жанр', 'verbose_name_plural': 'Избранные жанры'},
        ),
        migrations.AlterModelOptions(
            name='favoriteplaylists',
            options={'verbose_name': 'Избранный плейлист', 'verbose_name_plural': 'Избранные плейлисты'},
        ),
        migrations.AlterModelOptions(
            name='favoritetracks',
            options={'verbose_name': 'Избранный трек', 'verbose_name_plural': 'Избранные треки'},
        ),
    ]
